# -*- coding: utf-8 -*-
"""PythonProblem9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fz-Sq7Ipoo0ENNqq-xq2f8lqI865t21q

Problem 9: Use try, except/catch and finally block and catch divide by zero error. If error occures then show error message 'DIVIDE BY ZERO ERROR' in console.   
Solution:
"""

#Function which will handle errors by try and except block
def divide(x, y):
    try:
        # Floor Division : Gives only Fractional part as answer
        result = x // y
    except ZeroDivisionError:
        print("DIVIDE BY ZERO ERROR ")
    else:
        print("Answer is :", result)
    finally: 
        # this block is always executed  
        # regardless of exception generation. 
        print('You just did floor Division of ',x, "and" ,y)

#Calling function
divide(7, 2)

divide(3, 0)

